sudo: false
language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install coveralls coverage
  - pip install -r requirements.txt

script:
  - coverage run --source=bbws test.py

after_success:
  coveralls

notifications:
  email: false
